# Generated by Django 3.1.2 on 2020-10-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_auto_20201018_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformarquivo',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/'),
        ),
    ]
