# Generated by Django 3.1.2 on 2020-10-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0003_auto_20201018_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelformarquivo',
            name='conteudo',
            field=models.CharField(blank=True, max_length=999999, null=True),
        ),
    ]
