# Generated by Django 3.1.2 on 2020-10-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0006_caracteresarquivo_caractere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caractere', models.CharField(max_length=999999)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('arquivo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='desafio.modelformarquivo')),
            ],
        ),
        migrations.DeleteModel(
            name='CaracteresArquivo',
        ),
    ]
