# Generated by Django 3.1.2 on 2020-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0007_auto_20201018_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteres',
            name='sequencia',
            field=models.IntegerField(default=1, verbose_name='Sequencia'),
            preserve_default=False,
        ),
    ]
