# Generated by Django 3.1.2 on 2020-10-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0008_caracteres_sequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteres',
            name='versao',
            field=models.IntegerField(default=1, verbose_name='Versão'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Linhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('linha', models.IntegerField(verbose_name='Linha')),
                ('versao', models.IntegerField(verbose_name='Versão')),
                ('arquivo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='desafio.modelformarquivo')),
            ],
        ),
    ]
