# Generated by Django 3.1.2 on 2020-10-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0009_auto_20201020_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteres',
            options={'ordering': ('id', 'caractere'), 'verbose_name': 'Caractere', 'verbose_name_plural': 'Caracteres'},
        ),
        migrations.AlterModelOptions(
            name='linhas',
            options={'ordering': ('id', 'linha'), 'verbose_name': 'Linha', 'verbose_name_plural': 'Linhas'},
        ),
        migrations.AddField(
            model_name='modelformarquivo',
            name='versao',
            field=models.IntegerField(default=1, verbose_name='Versao'),
            preserve_default=False,
        ),
    ]
