# Generated by Django 3.1.2 on 2020-10-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0011_auto_20201020_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformarquivo',
            name='conteudo',
            field=models.TextField(blank=True, null=True, verbose_name='Conteudo'),
        ),
    ]
