# Generated by Django 3.1.2 on 2020-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0012_auto_20201020_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteres',
            name='palavra',
            field=models.CharField(default=1, max_length=900),
            preserve_default=False,
        ),
    ]
