# Generated by Django 3.1.2 on 2020-10-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0013_caracteres_palavra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteres',
            name='palavra',
        ),
        migrations.AddField(
            model_name='caracteres',
            name='asci',
            field=models.CharField(default=1, max_length=999999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caracteres',
            name='caractere',
            field=models.CharField(max_length=900),
        ),
    ]
