# Generated by Django 3.1.2 on 2020-10-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0014_auto_20201024_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelformarquivo',
            name='conteudo_refatorado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conteúdo refatorado'),
        ),
    ]
