# Generated by Django 3.1.2 on 2020-10-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0017_palavras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=999999)),
                ('inteiro', models.IntegerField()),
                ('double', models.DecimalField(decimal_places=2, max_digits=999999)),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'ordering': ('id', 'numero'),
            },
        ),
        migrations.AlterModelOptions(
            name='palavras',
            options={'verbose_name': 'Caractere', 'verbose_name_plural': 'Caracteres'},
        ),
    ]
