# Generated by Django 3.1.2 on 2020-10-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0018_auto_20201025_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeros',
            old_name='double',
            new_name='decimal',
        ),
    ]
