# Generated by Django 3.1.2 on 2020-10-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0019_auto_20201025_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeros',
            name='asci',
            field=models.CharField(default=1, max_length=999999),
            preserve_default=False,
        ),
    ]
